# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  deployments: write
      
jobs:

  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17.x'
        cache-dependency-path: go.sum

    - name: Install dependencies
      run: |
        go get .
          
    - name: Build
      run: go build -o ./dist/git_hook -v ./...

    - uses: vimtor/action-zip@v1
      with:
        files: dist/
        dest: git_hook.zip
    - uses: ncipollo/release-action@v1
      with:
        artifacts: git_hook.zip
